# My frist GitHub action
name: Run from my script

on:
  push:

jobs:
  run-from-my-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install cowpy
      run: pip install cowpy
    - name: run my script
      run: python examlpe.py


